# # service-internal.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app-internal
# spec:
#   type: ClusterIP
#   ports:
#   - port: 80kuv  
#     targetPort: 8000
#   selector:
#     app: flask-app

# nodeport service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: flask-app